name: Publish ALPS Theme

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: sudo apt-get install php php-curl
      - uses: curl -sS https://getcomposer.org/installer -o composer-setup.php
      - uses: sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - uses: sudo composer self-update
      - uses: ./.github/actions/theme-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CDN_HOST: ${{ secrets.CDN_HOST }}
          CDN_USER: ${{ secrets.CDN_USER }}
          CDN_PRIVATE_KEY: ${{ secrets.CDN_PRIVATE_KEY }}
          CDN_PRIVATE_KEY_PASS: ${{ secrets.CDN_PRIVATE_KEY_PASS }}
          CDN_ROOT_PATH: ${{ secrets.CDN_ROOT_PATH }}
