name: Publish ALPS Theme

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/theme-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLOUDFLARE_R2_ACCESS_TOKEN: ${{ secrets.CLOUDFLARE_R2_ACCESS_TOKEN }}
