name: Publish PROD ALPS Theme

on:
  workflow_dispatch:
  inputs:
    releaseId:
      description: 'Release ID to publish'
      required: true

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - id: publish
        name: Publish Theme
        run: |
          npm run wp:theme:manual-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLOUDFLARE_R2_ACCESS_TOKEN: ${{ secrets.CLOUDFLARE_R2_ACCESS_TOKEN }}
